version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp:0.44.0
    steps:
      - run: 
          name: "Set NEMU_CPP_ROOT environment variable and create workspace directory"
          command: mkdir -p /workspace/projects/nemu/cpp && echo 'export NEMU_CPP_ROOT="/workspace/projects/nemu/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Nemu/C++ Core"
          command: cd /workspace/projects/nemu/cpp && git clone https://github.com/nemu-cpp/core.git && cd core/build-files/gnumake && make
      - run:
          name: "Install build dependency: Nemu/C++ WebFramework"
          command: cd /workspace/projects/nemu/cpp && git clone https://github.com/nemu-cpp/web-framework.git && cd web-framework/build-files/gnumake && make
      - run:
          name: "Install build dependency: Nemu/C++ MustacheTemplateEngine"
          command: cd /workspace/projects/nemu/cpp && git clone https://github.com/nemu-cpp/mustache-template-engine.git && cd mustache-template-engine/build-files/gnumake && make
      - checkout:
          path: /workspace/projects/nemu/cpp/nemu
      - run:
          name: Build
          command: cd /workspace/projects/nemu/cpp/nemu/build/gnumake && make
      - run:
          name: "Build: Nemu/CLI"
          command: cd /workspace/projects/nemu/cpp/nemu/cli/build/gnumake && make
      - run:
          name: "Test: Nemu/CLI"
          command: cd /workspace/projects/nemu/cpp/nemu/cli/tests/build-files/gnumake && make && ./NemuCLITests

workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
