version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp:0.4.0
    steps:
      - run: 
          name: "Set NEMU_FRAMEWORK environment variable and create workspace directory"
          command: mkdir -p /projects/nemu-framework && echo 'export NEMU_FRAMEWORK="/projects/nemu-framework"' >> $BASH_ENV
      - checkout:
          path: /projects/nemu-framework/nemu
      - run:
          name: Build Nemu/Core
          command: cd /projects/nemu-framework/nemu/core/build/gnumake && make
